#!/bin/bash
python3 -m py_compile $PYFILE
mv __pycache__/*.pyc ${PYFILE}c
rm -rf __pycache__
#python3 -c "import py_compile; py_compile.compile('$PYFILE', cfile='${PYFILE}c')"
#python3 -m compileall -b $PYFILE i
